### ISSUE TITLE
Problems experienced with SSL certificates using requests library

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/python-installer-qt-gui#83]
As reported by @kmahajan-cadfem, he has experienced issues when downloading Python using the Ansys Python Manager. Errors seem to be related to SSL Certificate verification when using the ``requests`` library. One option would be to implement as a fail-safe a powershell web request directly. See #82 for more details.

Proposed solution by @kmahajan-cadfem:

> one solution could be to just create a powershell web request, instead of python requests. (as fail safe)
> 
> ```powershell
> Invoke-RestMethod 'https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe' -Method 'GET'  -OutFile "python-3.10.0.exe"
> ```
> 
> or just use `wget`, should be available on windows as well under powershell.
> 

_Originally posted by @kmahajan-cadfem in https://github.com/pyansys/python-installer-qt-gui/issues/82#issuecomment-1525117157_

**Comment by RobPasMue** [comment]
@kmahajan-cadfem could you try something on the script you posted on https://github.com/pyansys/python-installer-qt-gui/issues/82#issuecomment-1525039594
 
 Try calling it as follows:
 
```py
    session = requests.Session()
    response = session.get(
        url, allow_redirects=True, stream=True, headers=request_headers, verify=False
    )
```

Main difference is adding the last argument: ``verify=False``. Check if it works like that

**Comment by RobPasMue** [comment]
Another option after this first trial would be to run ``pip install --upgrade certifi``, updating symlinks to certificates and then running it without the ``verify=False`` argument. 

More info is here https://stackoverflow.com/a/4233435. Though it is especially oriented for OSX it should be applicable everywhere :)

This is just a different attempt to understand the root cause.

**Comment by RobPasMue** [comment]
Okay got it.  Let's go with the powershell commands then. Thanks for testing it @kmahajan-cadfem!

**Comment by RobPasMue** [comment]
Hi @kmahajan-cadfem! We just did a new release 0.2.0!! In this release, we included a potential solution for your issue, could you check if it works for you now? Thanks in advance! You can easily update your up by clicking on ``File >> Check for updates`` on your Ansys Python Manager installation. Looking forward to your feedback =)

**Comment by kmahajan-cadfem** [comment]
Hi @RobPasMue 
Thanks for quick fix.
1. This works for downloading now, I cannot install Python because of `Admin Rights`. That is fine for now.
2. I have also encountered  SSL problem with updater 

![grafik](https://user-images.githubusercontent.com/82146655/235189287-b5c4ba97-60c0-42a1-97e6-655ff6ae371b.png)


I am not really sure where these SSL problems are arising from exactly, because I can access everything over the browser without any problems.

**Comment by RobPasMue** [comment]
Interesting... that happened when updating the app through the ``File >> Check for updates`` mechanism?

**Comment by RobPasMue** [comment]
I will open a new issue for tracking this
