### ISSUE TITLE
no shortcuts for user if Installation is done by ADMIN

### ISSUE THREAD

**Issue by kmahajan-cadfem** [pyansys/python-installer-qt-gui#98]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

on Windows
If Admin does the installation then by default `NSIS` creates shortcut only for this user, in this case `Admin`.

this would not help if some one wants to deploy this installer company wide. and since it is installed for all users on this machine, like Ansys, it would be better to create shortcut for all.

### 📝 Steps to reproduce

- Install tool using `user1`
- switch account, look for Ansys Python Manager in start menu

following is the solution for this problem

```nsis
; Create the start menu shortcut for all users
  SetShellVarContext all
  CreateShortCut "$SMPROGRAMS\Ansys Python Manager\Ansys Python Manager.lnk" "$INSTDIR\Ansys Python Manager.exe"
  SetShellVarContext current
  CreateShortCut "$SMPROGRAMS\Ansys Python Manager\Ansys Python Manager.lnk" "$INSTDIR\Ansys Python Manager.exe"
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023 R1

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
-
```

**Comment by RobPasMue** [comment]
Interesting feature. Definitely useful. We might consider using this instead https://nsis.sourceforge.io/Docs/MultiUser/Readme.html

**Comment by RobPasMue** [comment]
Hi @kmahajan-cadfem! Just implemented it. Admin-privilege users can now perform all-users installations. If a user does not have these privileges, they won't be given the option. Thanks for the suggestion!

There is a new patch release of version 0.2 (i.e. 0.2.2) that has this feature implemented! Let us know if you experience any issues!

**Comment by kmahajan-cadfem** [comment]
> Hi @kmahajan-cadfem! Just implemented it. Admin-privilege users can now perform all-users installations. If a user does not have these privileges, they won't be given the option. Thanks for the suggestion!
> 
> There is a new patch release of version 0.2 (i.e. 0.2.2) that has this feature implemented! Let us know if you experience any issues!

Thanks for the implementation , it works like charm 🥇

**Comment by RobPasMue** [comment]
Glad it worked! Thanks for the feedback @kmahajan-cadfem!!
